hostname: keycloak
http-enabled: true
https-enabled: false
proxy-edge: false

db: postgres
db-url: jdbc:postgresql://postgres:5432/keycloak
db-username: keycloak
db-password: ${DB_PASSWORD:changeme}

admin-user: admin
admin-password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

log-level: INFO
